server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2b8
    username: root
    password: ws031103

mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描mybatis的xml文件以实现动态sql
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:\JetBrains\SpringBootFiles\BookShop\files\
#    要不要最后加"\"?
